// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static   FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['webapiKey']!,
    appId: dotenv.env['webappId']!,
    messagingSenderId: dotenv.env['webmessagingSenderId']!,
    projectId: dotenv.env['webprojectId']!,
    authDomain: dotenv.env['webauthDomain']!,
    storageBucket: dotenv.env['webstorageBucket']!,
    measurementId: dotenv.env['webmeasurementId']!,
  );
 
  static   FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['androidapiKey']!,
    appId: dotenv.env['androidappId']!,
    messagingSenderId: dotenv.env['androidmessagingSenderId']!,
    projectId: dotenv.env['androidprojectId']!,
    storageBucket: dotenv.env['androidstorageBucket']!,
  );

  static   FirebaseOptions ios = FirebaseOptions(
    apiKey:dotenv.env['iosapiKey']!,
    appId: dotenv.env['iosappId']!,
    messagingSenderId: dotenv.env['iosmessagingSenderId']!,
    projectId: dotenv.env['iosprojectId']!,
    storageBucket: dotenv.env['iosstorageBucket']!,
    iosBundleId: dotenv.env['iosiosBundleId']!,
  );

  static   FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['macosapiKey']!,
    appId: dotenv.env['macosappId']!,
    messagingSenderId: dotenv.env['macosmessagingSenderId']!,
    projectId: dotenv.env['macosprojectId']!,
    storageBucket: dotenv.env['macosstorageBucket']!,
    iosBundleId: dotenv.env['macosiosBundleId']!,
  );

  static   FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['windowsapiKey']!,
    appId: dotenv.env['windowsappId']!,
    messagingSenderId: dotenv.env['windowsmessagingSenderId']!,
    projectId: dotenv.env['windowsprojectId']!,
    authDomain: dotenv.env['windowsauthDomain']!,
    storageBucket: dotenv.env['windowsstorageBucket']!,
    measurementId: dotenv.env['windowsmeasurementId']!,
  );
}
